apiVersion: v1
kind: Pod
metadata:
  name: memory-hog
  namespace: demo
spec:
  restartPolicy: Always
  containers:
    - name: hog
      image: polinux/stress
      resources:
        limits:
          memory: "64Mi"
        requests:
          memory: "32Mi"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "128M", "--vm-hang", "1"]
