apiVersion: v1
kind: Pod
metadata:
  name: slow-memory-hog
  namespace: demo
spec:
  restartPolicy: Always
  containers:
  - name: hog
    image: polinux/stress
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--timeout", "120"]

